# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bac66ddccefd96a778668d816fed75b868177c8c2fe4809580173dc24c2545610ef2d92d2ce3554b1971d661bf06b2f5c5b01ffd8264f3a9076193e600e01972

test:
  secret_key_base: 0c26a649e43f1c746617e866b7f98c6a253aec417d5ca7345392dbf0c51c02f0ff25ecbffd48459d57aa6fe15e3a822f41df94648148b1a9122bacfa6d67d124

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
